services:
  - name: laravel-app
    type: web
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false   # Esto se generará automáticamente en start.sh si no existe
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cvk2plruibrs739sj38g-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: pruebarender_db
      - key: DB_USERNAME
        value: pruebarender_db_user
      - key: DB_PASSWORD
        sync: false   # Agregarás esta contraseña manualmente en el panel de Render
    region: oregon
    plan: free
    buildCommand: ""        # ⚠️ Vacío, ya que composer install está en el Dockerfile
    startCommand: "./start.sh"  # ✅ Tu script que espera la base de datos y ejecuta migraciones
