services:
  - name: laravel-app
    type: web
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: base64:6u+iaWkYzs65EVca+VWcSplomFn45HAZ1HvQUfgeRIk=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cvk2plruibrs739sj38g-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: pruebarender_db
      - key: DB_USERNAME
        value: pruebarender_db_user
      - key: DB_PASSWORD
        value: O2sW813IkSxZO4LTZ4mAaAZ5HEYwCydI
    region: oregon
    plan: free
    buildCommand: ""        # ⚠️ Vacío, ya que composer install está en el Dockerfile
    startCommand: "./start.sh"  # ✅ Tu script que espera la base de datos y ejecuta migraciones
